defaultPortal: MigrationBoilerplateModuleLibrary_November2022
portals:
  - name: MigrationBoilerplateModuleLibrary_November2022
    portalId: 23276397
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMzS9KTKMBIJAA0AAAAA4A0DGO3WjAsg8uWvDSju6QwyFFGNLFlNvKG1DRYtOEgxtzxoit0GOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQNHttCpmsotLYxyCrFH-Uvw-aDekoDbmExUgBaAA
        expiresAt: '2022-11-23T13:11:13.999Z'
    personalAccessKey: >-
      CiQ1OWYwZGJjNi00YTMxLTRlZGYtYTA1MS1jNDg0NGU5YWQxNmIQ7daMCxjy5a8NKhkABeaRgkhuzh8TLxC_PuI2PM3GmQS-HjKmSgNuYTE
