defaultPortal: MigrationBoilerplateModuleLibrary_November2022
portals:
  - name: MigrationBoilerplateModuleLibrary_November2022
    portalId: 23276397
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMLQyfnHMBIJAA0AAAAA4A0DGO3WjAsg8uWvDSju6QwyFBB5WL3-OylowR_jblgO-kCQ-FrKOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRbRKwSnYeV4SrTpA3VoaD98s7ZwUoDbmExUgBaAA
        expiresAt: '2022-11-16T06:48:40.773Z'
    personalAccessKey: >-
      CiQ1OWYwZGJjNi00YTMxLTRlZGYtYTA1MS1jNDg0NGU5YWQxNmIQ7daMCxjy5a8NKhkABeaRgkhuzh8TLxC_PuI2PM3GmQS-HjKmSgNuYTE
